#############################################################################
# Makefile for building: air
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  air.pro
# Template: app
# Command: D:\codePragram\Qt5.8\5.8\mingw53_32\bin\qmake.exe -o Makefile air.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = D:\codePragram\Qt5.8\5.8\mingw53_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: air.pro ../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/win32-g++/qmake.conf ../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/spec_pre.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/qdevice.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/device_config.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/common/angle.conf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/qconfig.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_charts.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_core.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_core_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_designer.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_gui.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_help.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_help_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_location.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_location_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_network.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_network_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_qml.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quick.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_script.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_script_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_sql.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_svg.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_xml.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/qt_functions.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/qt_config.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/win32-g++/qmake.conf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/spec_post.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/exclusive_builds.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/toolchain.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/default_pre.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/win32/default_pre.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/resolve_config.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/exclusive_builds_post.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/default_post.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/qml_debug.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/win32/rtti.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/precompile_header.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/warn_on.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/qt.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/resources.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/moc.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/win32/opengl.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/uic.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/qmake_use.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/file_copies.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/win32/windows.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/testcase_targets.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/exceptions.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/yacc.prf \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/lex.prf \
		air.pro \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/lib/qtmaind.prl \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/lib/Qt5Multimedia.prl \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/lib/Qt5Widgets.prl \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/lib/Qt5Gui.prl \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/lib/Qt5Network.prl \
		../../../../codePragram/Qt5.8/5.8/mingw53_32/lib/Qt5Core.prl
	$(QMAKE) -o Makefile air.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/spec_pre.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/qdevice.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/device_config.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/common/angle.conf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/qconfig.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_charts.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_charts_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_core.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_core_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_designer.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_gui.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_help.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_help_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_location.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_location_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_network.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_network_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_qml.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quick.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_script.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_script_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_sql.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_svg.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_xml.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/qt_functions.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/qt_config.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/win32-g++/qmake.conf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/spec_post.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/exclusive_builds.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/toolchain.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/default_pre.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/win32/default_pre.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/resolve_config.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/exclusive_builds_post.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/default_post.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/qml_debug.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/win32/rtti.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/precompile_header.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/warn_on.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/qt.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/resources.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/moc.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/win32/opengl.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/uic.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/qmake_use.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/file_copies.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/win32/windows.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/testcase_targets.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/exceptions.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/yacc.prf:
../../../../codePragram/Qt5.8/5.8/mingw53_32/mkspecs/features/lex.prf:
air.pro:
../../../../codePragram/Qt5.8/5.8/mingw53_32/lib/qtmaind.prl:
../../../../codePragram/Qt5.8/5.8/mingw53_32/lib/Qt5Multimedia.prl:
../../../../codePragram/Qt5.8/5.8/mingw53_32/lib/Qt5Widgets.prl:
../../../../codePragram/Qt5.8/5.8/mingw53_32/lib/Qt5Gui.prl:
../../../../codePragram/Qt5.8/5.8/mingw53_32/lib/Qt5Network.prl:
../../../../codePragram/Qt5.8/5.8/mingw53_32/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile air.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
